name: Build & Create Platform Branch

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command send to the platform-repository'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
      apps:
        description: "Application's Acronyms to deploy. Check the full list of available applications in 
        https://github.com/labforward/platform-deployment/blob/main/config/installation/activation.properties"
        type: string
        required: true
        default: '{fos}'

jobs:
  create-platform-branch:
    name: 'Build And Trigger Platform Deployment'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout actions'
        uses: actions/checkout@v3
      - name: 'Build with CircleCI and Deploy via Platform'
        uses: labforward/platform-gha/platform/delivery@0.0.8
        with:
          cci_token: ${{ secrets.CCI_TOKEN }}
          gh_pat: ${{ secrets.GH_PAT }}
          apps: ${{ inputs.apps }}
          chart_name: "file-object-storage-chart.yaml"