name: Build & Create Platform Branch

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command send to the platform-repository'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
      apps:
        description: "Application's Acronyms to deploy. Check https://github.com/labforward/platform-deployment/blob/main/config/installation/activation.properties"
        type: string
        required: true
        default: '{fos}'
      docker_build_job_name:
        description: "Name of the product's job that build and push the application's docker image"
        type: string
        required: true
        default: 'docker-build-and-push'

jobs:
  create-platform-branch:
    name: 'Build And Trigger Platform Deployment'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Build with CircleCI and Deploy via Platform'
        uses: labforward/platform-gha/platform/delivery@1.0.1
        with:
          cci_token: ${{ secrets.CCI_TOKEN }}
          gh_pat: ${{ secrets.GH_PAT }}
          apps: ${{ inputs.apps }}
          chart_name: "file-object-storage-chart.yaml"
          docker_build_job_name: ${{ inputs.docker_build_job_name }}
