name: 'Commit to Platform'

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command send to the platform-repository'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
      apps:
        description: "Application's Acronyms to deploy. Check https://github.com/labforward/platform-deployment/blob/main/config/installation/activation.properties"
        type: string
        required: true
        default: '{fos}'

jobs:
  create-platform-branch:
    name: 'Commit chartVersion to Platform Branch'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Create platform-deployment Branch'
        uses: labforward/platform-gha/platform/branch/create@0.0.8
        with:
          gh_pat: ${{ secrets.GH_PAT }}
          apps: ${{ inputs.apps }}
          chart_name: "file-object-storage-chart.yaml"
