name: Build Docker & Charts

on:
  workflow_dispatch:

jobs:
  circleci-docker-build:
    name: 'Trigger CircleCI Build'
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout actions'
        uses: actions/checkout@v3
      - name: 'Trigger CircleCI Build'
        uses: labforward/platform-gha/circleci/trigger@0.0.8
        with:
          cci_token: ${{ secrets.CCI_TOKEN }}